/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LocationProxyTest {
    @Test public void testLocationProxyCreation() {
        LocationProxy classUnderTest = new LocationProxy();
        assertNotNull("LocationProxy should create an object", classUnderTest);
//        assertNotNull("LocationProxy should serve post request", classUnderTest.doPost());
    }
}
